// Xe35 (CRI) shim TU for tile-fused MXFP4-B × BF16-A MoE grouped GEMM.
// Links against the AOT-compiled launcher instances generated by
// src/GroupGemmMxfp4W4A16Xe20.cmake for SYCL_INTEL_TARGET=35.
// See src/sycl/kernels/moe/xe35/GroupGemmMxfp4W4A16.hpp for the rationale.
#define SYCL_INTEL_TARGET 35

#include "../kernels/moe/xe35/GroupGemmMxfp4W4A16.hpp"

#undef SYCL_INTEL_TARGET
